url: https://www.innopam.co.kr/
baseurl: .

# Site settings
title: INNOPAM
email: jypark.inno@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/innopam
  - title: facebook
    url: http://facebook.com/innopam
  - title: bitbucket 
    url: http://bitbucket.org/innopam
  - title: github
    url: http://github.com/innopam

# Postal address (add as many lines as necessary)
address:
  - line: InnoPAM HQ, 63, Seoulsiripdae-ro, Dongdaemun-gu, Seoul, Republic of Korea
  - line: InnoPAM Lab, 3F, 77, Cheongpa-ro, Yongsan-gu, Seoul, Republic of Korea

# Build settings
markdown: kramdown
permalink: pretty

collections:
  solutions:
    output: true